language: perl
addons:
  apt:
    packages:
      - libsnmp-dev
branches:
  only:
    - /^3\.\d{2}$/
    - 'master'
install: true
script: |
  perl Build.PL && \
  ./Build && \
  PERL_MM_USE_DEFAULT=1 ./Build installdeps --cpan_client 'cpanm --quiet --notest' && \
  ./Build test --test_files t/ --test_files xt/
notifications:
  irc:
    on_success: always
    channels:
      - 'chat.freenode.net#netdisco'
