name: GitHub Release on Tag
on:
  push:
    tags:
      - '2.[0-9][0-9][0-9][0-9][0-9][0-9]'
jobs:
  release_snmp_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the Tag
        id: get_tag
        run: echo ::set-output name=TAGVALUE::${GITHUB_REF#refs/tags/}
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: SNMP::Info ${{ steps.get_tag.outputs.TAGVALUE }}
